# Clear all objects from the environment
rm(list=ls())

# Set the working directory
folder <- "/Users/sunjiajing/Desktop/Hong2020/advance time series analysis -20240328/R代码/advanced-time-series-chapter1"
setwd(folder)

# Read the data
sse <- read.csv("sse.csv")

# Ensure the date column is of type Dates
sse$Date <- as.Date(sse$Date)

# Use ggplot2 to plot the SSE Index over time
sse_plot <- ggplot(sse, aes(x = Date, y = SSE)) +
  geom_line(color = "blue") +  
  labs(title = "SSE Index Over Time", x = "Date", y = "SSE Index") +
  theme(
    panel.grid.major = element_line(color = "grey80"),
    panel.grid.minor = element_blank(),
    panel.background = element_rect(fill = "white"),
    plot.background = element_rect(fill = "white", colour = NA),
    axis.line = element_line(color = "black")
  )

# Display the chart
print(sse_plot)

# Save the chart as a PNG file
ggsave("sse_index_plot.png", plot = sse_plot, width = 10, height = 6)

# Calculate log returns
sse$Log_Returns <- c(NA, diff(log(sse$SSE)))
sse <- na.omit(sse) # Remove NA values generated by differencing

# Split the data into training and testing sets (95% training, 5% testing)
split_index <- floor(0.80 * nrow(sse))
train_data <- sse$Log_Returns[1:split_index]
test_data <- sse$Log_Returns[(split_index + 1):nrow(sse)]

# Load necessary libraries
library(tseries)
library(forecast)
library(ggplot2)
library(dplyr)

# Save ACF plot of residuals as a PNG file
png(file = "acf_SSE.png")
acf(train_data)
dev.off() # Close the graphic device

# Save PACF plot of residuals as a PNG file
png(file = "pacf_SSE.png")
pacf(train_data)
dev.off() # Close the graphic device

# Fit an ARIMA model to the training data
model <- auto.arima(train_data)
summary(model)

# Use the model to make predictions on the testing data
forecasts <- forecast(model, h = length(test_data))

# Prepare data for ggplot
train_df <- data.frame(Date = sse$Date[1:split_index], 
                       Value = train_data, Type = "Training Data")
forecast_df <- data.frame(Date = sse$Date[(split_index + 1):nrow(sse)], 
                          Forecast = forecasts$mean, Lower = forecasts$lower[, "80%"], 
                          Upper = forecasts$upper[, "80%"], Type = "Forecast Data")

# Plot with ggplot2 and set white background
final_plot <- ggplot() +
  geom_line(data = train_df, 
            aes(x = Date, y = Value, group = 1), 
            color = "black") +
  geom_line(data = forecast_df, 
            aes(x = Date, y = Forecast, group = 1), 
            color = "blue") +
  geom_ribbon(data = forecast_df, 
              aes(x = Date, ymin = Lower, ymax = Upper, group = 1), 
              fill = "blue", alpha = 0.2) +
  geom_point(data = data.frame(Date = sse$Date[(split_index + 1):nrow(sse)], 
                               Actual = test_data), 
             aes(x = Date, y = Actual), 
             color = "red") +
  scale_x_date(date_breaks = "3 month", 
               date_labels = "%Y-%m") +
  labs(title = "Training, Forecast and Actual Data", 
       x = "Date", 
       y = "Log Returns") +
  theme_minimal() +
  theme(
    panel.background = element_rect(fill = "white", colour = "black"),
    plot.background = element_rect(fill = "white", colour = NA)
  )

# Display the chart
print(final_plot)

# Save the chart as a PNG file
ggsave("forecast_plot.png", plot = final_plot, width = 10, height = 6)