##########################################################################################
# Density and Histogram of DAX Daily Returns from EuStockMarkets Dataset
##########################################################################################

# Clear workspace
rm(list = ls())

# Set working directory to the folder where this script is saved (only works in RStudio)
if (requireNamespace("rstudioapi", quietly = TRUE)) {
  setwd(dirname(rstudioapi::getActiveDocumentContext()$path))
}

# Load necessary libraries
# install.packages("ggplot2")  # Uncomment if not installed
library(datasets)
library(ggplot2)

##########################################################################################
# 1. Load and Prepare Data
##########################################################################################

# Load EuStockMarkets dataset
data("EuStockMarkets")

# Extract DAX prices
dax_prices <- EuStockMarkets[, "DAX"]

# Calculate daily returns as percentage change
dax_returns <- diff(dax_prices) / stats::lag(dax_prices, -1) * 100

# Remove NA values generated by differencing
dax_returns <- na.omit(dax_returns)

# Convert returns to data frame for plotting
dax_returns_df <- data.frame(DAX_Returns = as.numeric(dax_returns))

##########################################################################################
# 2. Plot and Save Histogram with Kernel Density Estimate
##########################################################################################

# Create plot
p <- ggplot(dax_returns_df, aes(x = DAX_Returns)) +
  geom_histogram(aes(y = ..density..), binwidth = 0.5, 
                 color = "black", fill = "blue") +
  geom_density(alpha = 0.2, fill = "#FF6666") +
  labs(
    title = "Density and Histogram of DAX Index Daily Returns",
    x = "Daily Returns (%)",
    y = "Density"
  ) +
  theme_minimal()

# Display plot
print(p)

# Save the plot as PNG
ggsave(filename = "DAX_Returns_Histogram_Density.png", plot = p, width = 8, height = 5, dpi = 300)
