## =====================================================
## 1. Load necessary libraries for data downloading 
##    and kernel density estimation
## =====================================================
library(quantmod)     # for data downloading
library(MASS)          # for kde function for kernel density estimation
library(ks)            # for multivariate kernel density estimation

## =====================================================
## 2. Download recent FTSE 100 & DAX data and compute returns
## =====================================================
getSymbols("^FTSE", src = "yahoo", from = "2024-01-01", auto.assign = TRUE)
getSymbols("^GDAXI", src = "yahoo", from = "2024-01-01", auto.assign = TRUE)

ftse_prices <- Cl(FTSE)            # closing prices for FTSE
dax_prices <- Cl(GDAXI)            # closing prices for DAX

# Calculate daily log returns as percentage changes
ftse_returns <- dailyReturn(ftse_prices, type = "log") * 100
dax_returns <- dailyReturn(dax_prices, type = "log") * 100

# Remove NA values generated by the dailyReturn function
ftse_returns <- na.omit(ftse_returns)
dax_returns <- na.omit(dax_returns)

# Convert to data frames with correct date index names
ftse_returns_df <- data.frame(Date = index(ftse_returns),
                              FTSE_Returns = coredata(ftse_returns))
dax_returns_df <- data.frame(Date = index(dax_returns),
                             DAX_Returns = coredata(dax_returns))

# Merge the data by date (ensure both data frames have the same Date column)
market_returns <- merge(ftse_returns_df, dax_returns_df, by = "Date", all = TRUE)

# Remove rows with NA values
market_returns_clean <- na.omit(market_returns)

# Rename columns to match the desired names
colnames(market_returns_clean) <- c("Date", "FTSE_Returns", "DAX_Returns")

## =====================================================
## 3. Perform Multivariate Kernel Density Estimation
## =====================================================
# Convert the cleaned data frame to a matrix for multivariate analysis
data_matrix <- as.matrix(market_returns_clean[, c("FTSE_Returns", "DAX_Returns")])

# Perform multivariate kernel density estimation using the ks package
kde_result <- kde(x = data_matrix)

## =====================================================
## 4. 2D and 3D Visualization using ks package
## =====================================================

# 2D visualization using filled contour plot
plot(kde_result, display = "filled.contour")

# 3D visualization using perspective plot
plot(kde_result, display = "persp")